### ISSUE TITLE
trying out try.wq: photos not showing in events

### ISSUE THREAD

**Issue by managingwholes** [powered-by-wq/try.wq.io#13]
In my installation of try.wq.io my photos and thumbnails aren't showing up in /events listings (where I get images/empty.png)

but they do show up in /reports.

In try.wq.io, they show up in both.

thanks for any help.

**Comment by sheppard** [comment]
Check to ensure that the `is_valid` flag is set on the "valid" `ReportStatus` instance.  (This should probably happen automatically, for now you can do it by running `./manage.py set_perms`).    See #14.

**Comment by managingwholes** [comment]
That worked, thanks. I then retracted the permissions to create and edit campaigns through the admin interface. The inner workings of the data model are still mysterious; I'll keep reading what you've written and hope it sinks in.
