### ISSUE TITLE
Javascript Error ```Uncaught TypeError: Cannot read property 'lat' of undefined```

### ISSUE THREAD

**Issue by joshglenn** [powered-by-wq/try.wq.io#2]
After getting `try.wq.io` installed, I ran it for the first time and I get a javascript error with the leaflet map. 

```
Uncaught TypeError: Cannot read property 'lat' of undefined
```

![screen shot 2015-11-06 at 11 15 15 pm](https://cloud.githubusercontent.com/assets/6953274/11013453/7bbd98ea-84dc-11e5-8978-fa446a3c0a92.png)

Any idea what could cause this?

**Comment by sheppard** [comment]
This is a harmless bug in wq/map.js - it will go away once there is data to show in the map.

**Comment by joshglenn** [comment]
Ok. Great. Thanks!
