### ISSUE TITLE
Trying out try.wq.io. Cannot add custom fields.

### ISSUE THREAD

**Issue by joshglenn** [powered-by-wq/try.wq.io#4]
See photo for the javascript error:

![screen shot 2015-11-11 at 1 45 06 am](https://cloud.githubusercontent.com/assets/6953274/11085613/7c30f942-8816-11e5-9d64-1eb4f57b0c9f.png)

**Comment by sheppard** [comment]
I haven't been able to reproduce this - It's odd that jQuery Mobile would not be defined at this point.  Are there any Chrome extensions that could be causing this?  I notice a lot of additional Sources in the list.
