### ISSUE TITLE
trying out try.wq: oauth2 implementation, admin access

### ISSUE THREAD

**Issue by managingwholes** [powered-by-wq/try.wq.io#5]
Would you be able to advise me on implementing oauth2? I have client ID and secret but no idea what to do with them.

Also, getting errors while trying to access the admin portion. What could I be missing? I've created superuser but navigating to site/admin yields this:

Using the URLconf defined in atlasbiowork.urls, Django tried these URL patterns, in this order:
^generate/
^login/(?P<backend>[^/]+)/$ [name='begin']
^complete/(?P<backend>[^/]+)/$ [name='complete']
^disconnect/(?P<backend>[^/]+)/$ [name='disconnect']
^disconnect/(?P<backend>[^/]+)/(?P<association_id>[^/]+)/$ [name='disconnect_individual']
^ ^relationships$ [name='relationship-list']
^ ^relationships.(?P<format>[a-z0-9]+)/?$ [name='relationship-list']
^ ^relationships/(?P<pk>[^/.]+)$ [name='relationship-detail']
^ ^relationships/(?P<pk>[^/.]+).(?P<format>[a-z0-9]+)/?$ [name='relationship-detail']
etc

thanks
P

**Comment by sheppard** [comment]
As you noted, the Django admin site is not configured with Try WQ (mostly an arbitrary decision on my part).  You just need to add it to `INSTALLED_APPS` in `settings.py` as well as to your `urls.py`.

(See #3 for OAuth usage, #6 for more admin notes)
