### ISSUE TITLE
trying out try.wq.io: gaining access to models in admin interface

### ISSUE THREAD

**Issue by managingwholes** [powered-by-wq/try.wq.io#6]
I've got the admin interface going, but it's not connecting with its stylesheets (e.g. myapp/static/admin/css/base.css or dashboard.css) and it gives me no admin access to Events, Reports, Campaigns. There is a Vera heading which only gives access to Report Statuses and Sites.

Any ideas on what I'm missing?

**Comment by sheppard** [comment]
You should be able to run `./manage.py collectstatic` to get the necessary files for the admin interface.

As to the missing models, you'll just need to create a file `campaigns/admin.py` and [register the models with the admin](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#modeladmin-objects).  You might as well use [vera's admin classes](https://github.com/wq/vera/blob/master/vera/admin.py) which include support for e.g. nested `Result` models.  (vera defines the classes but only registers them if the models haven't been customized).

``` python
from django.contrib import admin
from vera.admin import EventAdmin, ReportAdmin

from .models import Event, Report, Campaign

admin.site.register(Event, EventAdmin)
admin.site.register(Report, ReportAdmin)
admin.site.register(Campaign)

```

**Comment by managingwholes** [comment]
Thanks Andrew. I also added a line in urls.py to include the admin patterns and it all works now.

**Comment by tubaman** [comment]
@sheppard, it looks like [admin support has been removed](https://github.com/wq/wq.db/issues/38).  Any plans to bring it back?
